### ISSUE TITLE
Datálogo

### ISSUE THREAD

**Issue by almaosorio** [GobCDMX/politicadedatos#101]
![image](https://user-images.githubusercontent.com/62679070/100041765-a256a680-2dcf-11eb-9afe-2cb25394cbd3.png)

Creo que aquí hay que añadir, al final: ¿Cómo se verá ell datálogo en 2021? 
Queremos construir una herramienta para que los Entes Públicos puedan administrar su metadatos, consultarlos, y poder explorar los metdatos de los demás.

**Comment by almaosorio** [comment]
https://gobcdmx.github.io/politicadedatos/datalogo @mfuentesbo qué opinas?

**Comment by mfuentesbo** [comment]
Si, me gusta. Lo agrego
