### ISSUE TITLE
quitar el link a siguientes pasos

### ISSUE THREAD

**Issue by almaosorio** [GobCDMX/politicadedatos#102]
https://gobcdmx.github.io/politicadedatos/datalogo/como_se_construira 

Al final quitar: Para conocer las fechas en las que se llevará a cabo cada fase consulta nuestros siguientes pasos. ( ya que pondremos cada una de las fases como children del parent). O qué opinas @mfuentesbo

**Comment by mfuentesbo** [comment]
No me late quitarlo. Siento que los siguientes pasos son una vista rápida de fechas bastante útil.
