### ISSUE TITLE
Cambiar el título de la tabla

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#11]
Cambiar el título de la tabla para que se adecue a las modificaciones que se hicieron y quede: **Especificaciones técnicas de la Ficha Estándar de Metadatos para cualquier conjunto de datos para cualquier base o conjunto de datos y capas geográficas**

Aunque..... resulta muy grande; entonces, la segunda opción sería dejarlo solo como: 
**Especificaciones técnicas de la Ficha Estándar de Metadatos**

**Comment by almaosorio** [comment]
El segundo.
