### ISSUE TITLE
Pensar en esto

### ISSUE THREAD

**Issue by almaosorio** [GobCDMX/politicadedatos#117]
![image](https://user-images.githubusercontent.com/62679070/100474360-06b28800-30a6-11eb-9f72-9b1cee4e616b.png)

**Comment by mfuentesbo** [comment]
No se que opinas de algo así:

¿Todos los metadatos del inventario de datos de la ciudad (Datálogo) serán explorables? 

No, solo serán explorables aquellos metadatos que por su naturaleza no se consideran información sensible.

Metadatos de Sistemas de Información - Estos metadatos serán completamente confidenciales, y sólo se podrán consultar dentro de la Agencia para realizar diversos proyectos estratégicos existentes o que surjan en el futuro.

Metadatos de bases de datos, conjuntos de datos y capas geoespaciales - Se dividirán en dos grupos: reservados (metadatos sensibles) y no reservados. 

Los metadatos reservados de estos recursos serán completamente confidenciales, y sólo se podrán consultar dentro de la Agencia para realizar diversos proyectos estratégicos existentes o que surjan en el futuro.

Los metadatos no reservados se integrarán en una versión del Datálogo que podrán explorar unicamente los servidores públicos de las diferentes dependencias.

Administrador de metadatos: Cada Ente Público tendrá acceso a una herramienta para poder consultar y administrar sus metadatos para manetener esta información actualizada.

**Comment by almaosorio** [comment]
Me gusta, pero cambiaría lo que puse en negritas: 

Los metadatos no reservados se integrarán en una versión del Datálogo que podrán explorar **unicamente** los servidores públicos de las diferentes dependencias.

**Comment by almaosorio** [comment]
(o sea quitaría esa palabra)
