### ISSUE TITLE
Falta el link al portal de datos abiertos en la sección de datos abiertos

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#131]
En la sección de datos abiertos (https://politicadedatos.cdmx.gob.mx/datos_abiertos/), en donde dice "portal de datos abiertos", falta el link 

![image](https://user-images.githubusercontent.com/65377014/103693245-975e6c80-4f5e-11eb-8681-62e74e950cef.png)

**Comment by mfuentesbo** [comment]
@viriesc este no se como se hace para que el nombre en el sidebar sea link

**Comment by viriesc** [comment]
Este es issue viejito por que ka seccion de "portal de datos abiertos" si abre como link aparte 
![image](https://user-images.githubusercontent.com/37716983/103850497-00340a80-506d-11eb-974e-7da8bfff5cb2.png)
