### ISSUE TITLE
Orden de mención de las Temáticas

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#14]
Sería recomendable ordenar la manera en que se enlistan las temáticas a que pudieran pertenecer los datos. Ya sea: 
1) Hacerlo por orden alfabético, o 
2) Según los temas más importantes (por ejemplo, recreación, cultura y deporte, ponerlo al final). 

Otra cosa: Educación, ciencia y tecnologíaEmpleo y ocupación, se fueron juntas. Separarlas.

**Comment by alinmaat** [comment]
Están en orden alfabético para cada ente su tema es importante es mejor priorizar por orden alfabético y no por lo que nosotres pensemos más relevante
