### ISSUE TITLE
Formato y estilo

### ISSUE THREAD

**Issue by josemiguelmu** [GobCDMX/politicadedatos#19]
1) En la columna de Especificaciones, algunos textos están alineados hacia la izquierda y otros justificados. Visulamente se ve messy, creo que deberíamos homologar.

2) Algunos textos llevan punto al final y otros no. Homologar a que todos lleven.

3) Cuando se enlistan ejemplos debería dejarse un espacio entre el texto que lo antecede y la lista de ejemplos.

4) En Tipo de representación espacial, los nombres de los ejemplos aparecen en bold. Son el único caso en que se visualiza así, por lo que hay que homologar de igual forma para todos los casos.

**Comment by alinmaat** [comment]
Perfecto, lo checo en el doc
