### ISSUE TITLE
El valor de formato debería de ser especificado con mime types

### ISSUE THREAD

**Issue by unRob** [GobCDMX/politicadedatos#28]
Hola! Antes que nada súper rifades con este esfuerzo! 👏🏽

https://github.com/GobCDMX/politicadedatos/blob/565eb982aac88d97bd7447b1c8dafac3391b6151/_posts/2020-05-28-metadatos.html#L276

Sobre el formato, me gustaría proponer que el estándar adopte la especificación de la IETF para [MIME types](https://tools.ietf.org/html/rfc6838) en vez de la lista especificada en la línea que indico arriba. Las ventajas a mi modo de ver, se reducen a la amplia adopción de dicho estándar. En [esta página](https://developer.mozilla.org/es/docs/Web/HTTP/Basics_of_HTTP/MIME_types) del Mozilla Developer Network hay una buena descripción del estándar y cuenta con referencias directas a las listas de MIME types oficiales de IANA, que propongo sean utilizadas tal cual.

Espero sus comentarios, y nuevamente, gracias por llevar acabo ejercicios como este!

**Comment by almaosorio** [comment]
Hola Rob! Gracias por tu retro (y sorry por tardar tanto en contestar). Nos preocupa que sea poco accesible para los entes de la APCDMX. Como te podrás imaginar, el desarrollo de capacidades de datos aún está muy verde...
