### ISSUE TITLE
Es "Marco PARA la gestión de datos" y no "de la gestión"

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#44]
Perdón Viri, esto seguro fue error mío, siempre me confundo, pero es MARCO PARA LA GESTIÓN DE DATOS. En el primer bullet de "En conjunto, se compone de:"
![image](https://user-images.githubusercontent.com/65377014/98890396-806d3380-2461-11eb-87c4-564536bcdf77.png)

**Comment by mfuentesbo** [comment]
Listo
