### ISSUE TITLE
Poner el párrafo introductorio de "Introducción a la gestión de datos" en Cultura de Datos

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#46]
Este párrafo introductorio se ve mejor en Cultura de Datos en General. 
![image](https://user-images.githubusercontent.com/65377014/98892875-dbedf000-2466-11eb-823d-f927671aa72b.png)

Para la sección de "Introducción a la gestión de datos" puedes poner lo siguiente: 

Aquí puedes consultar unas presentaciones básicas sobre el objetivo de la Política de Gestión de Datos, sobre qué son los datos, la diferencia entre bases de datos y conjuntos de datos; así como sobre diccionarios de datos y metadatos. 

Esta sección irá creciendo paulatinamente, espera más contenido.

**Comment by mfuentesbo** [comment]
Este ya quedó, aunque creo que estaría mejor que el de cultura e intro a la gestión fueran uno mismo. Si no siento que se ve medio vacía cada página
