### ISSUE TITLE
En la sección de "Diccionarios de datos" poner bien el nombre

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#51]
El nombre de la sección debe ser:  Guía práctica para la elaboración de diccionarios de datos 

luego ya viene lo de "qué es un diccionario de datos"...

**Comment by mfuentesbo** [comment]
Aquí hay que definir que hacemos porque el nombre tiene que ser el mismo en el sidebar y la sección

**Comment by mfuentesbo** [comment]
Que queden como:
- Cómo tener datos de calidad en hojas de cálculo
- Elaboración de diccionarios de datos
- Elaboración de catálogos de referencia
