### ISSUE TITLE
Sección Datálogo hay un bullet de más

### ISSUE THREAD

**Issue by Daliliuxurius** [GobCDMX/politicadedatos#56]
En la sección Datálogo/qué es (https://gobcdmx.github.io/politicadedatos/datalogo#qu%C3%A9-es), hay un bullet de más
![image](https://user-images.githubusercontent.com/65377014/98895276-5a995c00-246c-11eb-962e-8e343cf1efe3.png)

**Comment by mfuentesbo** [comment]
De hecho en general está mal el texto de los bullets, debe ser el que puse en uno de los issues pasados:

El Datálogo servirá para:
- Identificar, registrar y enumerar los recursos de tecnologías de información (link al glosario) de la Administración Pública de la Ciudad de México.
- Buscar, explorar y descubrir los metadatos de la Administración Pública.
- Facilitar la gestión y administración de los metadatos de los Entes Públicos.
- Facilitar el intercambio de datos entre los Entes de la Administración Pública al proporcionar información sobre los datos en su posesión, sus características y el estado en que se encuentran.
- Analizar y evaluar las necesidades tecnológicas e informáticas para gestionar los datos de la Ciudad de México.
- Promover una cultura de datos y prácticas de gestión de datos.
