### ISSUE TITLE
En general vamos a decir entes u organos desconcentrados?

### ISSUE THREAD

**Issue by mfuentesbo** [GobCDMX/politicadedatos#61]

**Comment by Daliliuxurius** [comment]
Entes, siempre Entes 
=P

**Comment by almaosorio** [comment]
100 pre entes

**Comment by mfuentesbo** [comment]
![Captura de pantalla 2020-11-24 095004](https://user-images.githubusercontent.com/13958036/100117502-791f3000-2e3a-11eb-8fbe-b27a1367f012.png)
Por ejemplo en este caso también es Entes en lugar de órganos autónomos?

**Comment by almaosorio** [comment]
Ah, es que órgano es una subcategoría de Ente en ese caso. Un órgano autónomo es un órgao autónomo jaja, eso no lo puedes cambiar. Resumen: 
Entes --> incluye organnos autónomos
Órganos públicos --> se usa como equivalente a Ente --> es distinto a órgano autónomo --> no lo vamos a usar

**Comment by mfuentesbo** [comment]
Que desmadre. Daré esto por cerrado y ya si encuentro otro caso raro lo pongo como nuevo issue jaja
