### ISSUE TITLE
En ¿Quienes participan? falta link a artículo de obligaciones en materia de gestión de datos

### ISSUE THREAD

**Issue by mfuentesbo** [GobCDMX/politicadedatos#62]
![Captura de pantalla 2020-11-12 163737](https://user-images.githubusercontent.com/13958036/99004919-7b61c000-2505-11eb-915c-ce959c65c26a.png)

**Comment by mfuentesbo** [comment]
Falta link de LOID

**Comment by Daliliuxurius** [comment]
Es el Artículo 16 de la LOID
