### ISSUE TITLE
Faltan PDFs del Marco para la Gestión de Datos

### ISSUE THREAD

**Issue by mfuentesbo** [GobCDMX/politicadedatos#64]
![Captura de pantalla 2020-11-12 165606](https://user-images.githubusercontent.com/13958036/99006380-f9bf6180-2507-11eb-81e1-b486f133f1d6.png)

**Comment by mfuentesbo** [comment]
Borrar pedazo de extendida

**Comment by Daliliuxurius** [comment]
Aquí está el PDF del Resumen ejecutivo: https://drive.google.com/file/d/1YEwhKyf0sArBqAHK1VabdwpEMkxR5HXg/view?usp=sharing

**Comment by Daliliuxurius** [comment]
> Aquí está el PDF del Resumen ejecutivo: https://drive.google.com/file/d/1YEwhKyf0sArBqAHK1VabdwpEMkxR5HXg/view?usp=sharing

@mfuentesbo
