### ISSUE TITLE
Diseño responsivo

### ISSUE THREAD

**Issue by ttoralesr** [GobCDMX/politicadedatos#7]
La visualización de la tabla y del contenido en general se rompe desde el celular.

**Comment by alinmaat** [comment]
El encabezado de la tabla (Especificaciones técnicas de la Ficha Estándar de Metadatos para cualquier conjunto de datos) no está centrado y se recomienda sea de color blanco.
También se recomienda que los nombres de las columnas sean de color blanco, se pierde
