### ISSUE TITLE
Redacción en apartado: Estamos construyendo la política de datos de la Ciudad de México

### ISSUE THREAD

**Issue by ttoralesr** [GobCDMX/politicadedatos#8]
En la redacción que está al final de la página de inicio, hay un error de redacción, dice:"Agregaremos más recomendaciones cómo hacer datos de calidad en la Ciudad. ¿Te gustaría participar?". 
Debe decir "Agregaremos más recomendaciones sobre cómo hacer datos de calidad en la Ciudad, ¿te gustaría participar?".

**Comment by almaosorio** [comment]
cc @ponentesincausa
