### ISSUE TITLE
En el directorio unos correos aparecen como links y otros no. Además hay un error en uno de los registros

### ISSUE THREAD

**Issue by mfuentesbo** [GobCDMX/politicadedatos#81]
![Captura de pantalla 2020-11-12 182410](https://user-images.githubusercontent.com/13958036/99012545-4741cb80-2514-11eb-8cc1-23c8bd5a6a3b.png)

**Comment by Daliliuxurius** [comment]
Se repite también varias veces el registro de la Comisión para la Reconstrucción

**Comment by mfuentesbo** [comment]
Y los nombres no estan homologados a empezar con mayuscula y las demás en minúscula
