### ISSUE TITLE
Texto de preguntas frecuentes sigue incompleto

### ISSUE THREAD

**Issue by mfuentesbo** [GobCDMX/politicadedatos#82]
Decidir si lo llenamos o lo dejamos

**Comment by Daliliuxurius** [comment]
Hacer los siguientes arreglos: 

- [x] En la segunda pregunta "¿La Política es de observancia obligatoria?", poner Secretarías, Dependencias, Órganos Públicos.... etc, con MAYÚSCULAS. 
- [x] En la cuarta pregunta "¿Cuáles son las funciones de los OI?" el Artículo de la LOID donde vienen es el **Artículo 14**
- [x] En la sexta pregunta "Qué pasa si un Ente público no designa OI?" referenciar al **Artículo 14** de la LOID 
- [x] En la séptima pregunta "¿Dónde puedo encontrar más información sobre la designación de los OI?" debe llevar lo siguiente: 

El 7 de agosto de 2020 se publicó en la Gaceta Oficial de la Ciudad de México el Aviso por el que se informa a los titulares de los Órganos de la Administración Pública de la Ciudad de México, el periodo para acreditar a las personas servidoras públicas que fungirán como Oficiales de Información y Enlaces de las Alcaldías, ante la Agencia Digital de Innovación Pública; el cual puedes consultar aquí: http://data.consejeria.cdmx.gob.mx/portal_old/uploads/gacetas/35297f56e7b6c0db4aba623698da3bd8.pdf

- [x] En la última pregunta, agregar en la respuesta: con copia a la Dirección de Coordinación de Proyectos de Datos al correo aosorio@cdmx.gob.mx

**Comment by mfuentesbo** [comment]
Si es Entes en lugar de Organos publicos decentralizados verdad?
