### ISSUE TITLE
Falta un enter en "Dat

### ISSUE THREAD

**Issue by almaosorio** [GobCDMX/politicadedatos#94]
![image](https://user-images.githubusercontent.com/62679070/99862821-d9735080-2b60-11eb-92ce-d07a6716bd85.png)

**Comment by almaosorio** [comment]
En este link: https://gobcdmx.github.io/politicadedatos/datalogo/como_se_construira

**Comment by mfuentesbo** [comment]
Supongo que te referías a separar los dos artículos citados de la ley
